backend:
  name: github
  repo:ozlukasko-arch/web-lukasko
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "stranky"
    label: "Stránky"
    files:
      - file: "index.html"
        label: "Hlavná stránka"
        name: "index"
        fields:
          - {label: "Nadpis", name: "nadpis", widget: "string"}
          - {label: "Príbeh", name: "pribeh", widget: "markdown"}
