backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "stranka"
    label: "Obsah stránky"
    files:
      - file: "index.html"
        label: "Hlavná stránka"
        name: "home"
        fields:
          - {label: "Hlavný nadpis", name: "nadpis", widget: "string"}
          - {label: "Príbeh rodiny", name: "pribeh", widget: "markdown"}
          - {label: "Cieľová suma", name: "suma", widget: "string"}
